# written by chatgpt i am just learning actions
name: Flake8 Linter

on:
  push:
    branches:
      - "**"  # Run on all branches
  pull_request:
    branches:
      - "**"  # Run on all PRs

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Install Flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Get all Python files
      id: get-files
      run: |
        find . -name "*.py" >> $GITHUB_ENV

    - name: Run Flake8 on changed files
      run: |
        if [ -z "$CHANGED_FILES" ]; then
          echo "No Python files changed. Skipping lint."
        else
          echo "Linting changed files: $CHANGED_FILES"
          flake8 $CHANGED_FILES
        fi
